name: Deploy Laravel ke Rumahweb

on:
  push:
    branches:
      - main   # sesuaikan dengan branch utama kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Tambahkan known_hosts biar tidak ditanya fingerprint
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts

      - name: Deploy ke Server Rumahweb
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "
            cd /home/$SSH_USER/voxy-club-indonesia &&
            git pull origin main &&
            composer install --no-interaction --prefer-dist --optimize-autoloader &&
            npm install &&
            npm run build &&
            php artisan migrate &&
            php artisan config:clear &&
            php artisan cache:clear &&
            php artisan route:clear &&
            php artisan view:clear
          "

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}          # contoh: domainkamu.com atau IP server
      SSH_USER: ${{ secrets.SSH_USER }}          # contoh: username cPanel / SSH
      SSH_PORT: ${{ secrets.SSH_PORT }}          # contoh: 65002 (isi sesuai Rumahweb kasih)
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # hasil export private key dari PuTTY ke OpenSSH
