name: Deploy Laravel ke Rumahweb

on:
  push:
    branches:
      - main   # Jalankan tiap kali ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install dependency Laravel & build asset
      - name: Install Dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader
          npm install && npm run build

      # 3. Upload hasil build ke server Rumahweb
      - name: Deploy ke Rumahweb via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude ".git*" --exclude "node_modules" --exclude ".env"
          path: ./ 
          remote_path: /home/voxa7613/voxy-club-indonesia/    # Ganti USERNAME
          remote_host: voxyclubindonesia.com                # Ganti domain atau IP Rumahweb
          remote_user: voxa7613                       # Ganti username SSH
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 4. Jalankan perintah Artisan di server
      - name: Jalankan Artisan Commands di Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: voxyclubindonesia.com
          username: voxa7613
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/voxa7613/voxy-club-indonesia
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
